name: testsuite

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:

jobs:

##
## A very light and cheap workflow using the default ubuntu container
##    a failure here will block all later workflows
##

  ubuntu:
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: perl -V
      - name: Makefile.PL
        run: perl -I$(pwd) Makefile.PL
      - run: make test

##
## Test multiple versions of Perl using perl-tester
##

  perl-versions:
    runs-on: ubuntu-latest
    name: List Perl versions
    outputs:
      perl-versions: ${{ steps.action.outputs.perl-versions }}
    steps:
      - id: action
        uses: perl-actions/perl-versions@v1
        with:
          since-perl: v5.8
          with-devel: true

  linux:
    name: "linux ${{ matrix.perl-version }}"
    needs:
      - ubuntu
      - perl-versions
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version: ${{ fromJson (needs.perl-versions.outputs.perl-versions) }}

    container: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v4
      - run: perl -V
      - name: Makefile.PL
        run: perl -I$(pwd) Makefile.PL
      - run: make test

  perl-56:
    name: "Perl 5.6"
    needs: [ubuntu]
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    runs-on: ubuntu-latest

    container:
      image: perldocker/perl:5.6

    steps:
      # cannot use v4 with that container
      - uses: actions/checkout@v3
      - run: perl -V
      - name: Makefile.PL
        run: perl -I$(pwd) Makefile.PL
      - run: make test
